version: "3"
services:
 nginx:
  image: nginx
  ports:
  - 8050:80
 alpine:
  image: alpine
  entrypoint: "wget http://www.google.com"
  depends_on:
  - nginx
  working_dir: /a/b/c
  volumes:
  - ./vol:/a/b/c
